### ISSUE TITLE
[suggestion] A way to give a role if a user messes up

### ISSUE THREAD

**Issue by BannerBomb** [gleeny/countr#2]
It would be nice if there was a way to set a max number of mistakes a user can get before getting a role, which can be configured in the channel settings to make it so they cannot count any more until the role is removed. And possibly a way to toggle if the bot should post stats like the top 3 counters usernames in the channel topic or not.

**Comment by gleeny** [comment]
Suggestion added; https://trello.com/c/e4s35cjt/33-when-someone-mess-up-x-amount-of-times-within-a-time-period-give-the-user-a-role - Please upvote it. Countr will be remade soon, this week I think. The code will get less messy as well.
